import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import prettier from "prettier";

const generatorVersion = "interior-design-continuity-generator-1.0.1";
const expectedOpenApiSha256 = "c5f4876952f321898ce4d8cda845bda73bb17b30f4e492bc3c43d3ebad4a2508";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const openApiPath = path.join(root, "openapi", "c14-cross-device-continuity-v1.json");
const typescriptPath = path.resolve(
  root,
  "..",
  "contracts",
  "src",
  "generated",
  "cross-device-continuity.ts",
);
const swiftRoot = path.join(root, "generated", "swift");
const swiftPackagePath = path.join(swiftRoot, "Package.swift");
const swiftSourcePath = path.join(
  swiftRoot,
  "Sources",
  "CrossDeviceContinuityClient",
  "CrossDeviceContinuityClient.swift",
);
const swiftTestPath = path.join(
  swiftRoot,
  "Tests",
  "CrossDeviceContinuityClientTests",
  "CrossDeviceContinuityClientTests.swift",
);

const openApiBytes = await readFile(openApiPath);
const openApi = JSON.parse(openApiBytes.toString("utf8"));
if (openApi.openapi !== "3.1.2" || openApi.info?.version !== "c14-cross-device-continuity-v1") {
  throw new Error("The continuity generator requires the frozen OpenAPI 3.1.2 contract.");
}
const operationIds = Object.values(openApi.paths ?? {}).flatMap((entry) =>
  Object.values(entry ?? {}).flatMap((operation) =>
    typeof operation?.operationId === "string" ? [operation.operationId] : [],
  ),
);
if (
  operationIds.length !== 2 ||
  !operationIds.includes("getOptionConfirmation") ||
  !operationIds.includes("listRenderEligibleSources")
) {
  throw new Error("The continuity OpenAPI operation set changed without a generator update.");
}
const openApiSha256 = createHash("sha256").update(openApiBytes).digest("hex");
if (openApiSha256 !== expectedOpenApiSha256) {
  throw new Error(
    "The frozen continuity OpenAPI bytes changed without a versioned generator contract update.",
  );
}
const banner = `Generated by ${generatorVersion} from OpenAPI SHA-256 ${openApiSha256}.`;
const prettierConfig = (await prettier.resolveConfig(typescriptPath)) ?? {};

function typescriptSource() {
  return `/* ${banner} Do not edit. */
export const continuityContract = Object.freeze({
  generatorVersion: "${generatorVersion}",
  openApiSha256: "${openApiSha256}",
  openApiVersion: "3.1.2",
  version: "c14-cross-device-continuity-v1",
} as const);

export interface OptionConfirmation {
  readonly branchId: string;
  readonly branchRevision: number;
  readonly commitId: string;
  readonly confirmedAt: string;
  readonly confirmedBy: string;
  readonly id: string;
  readonly idempotencyKey: string;
  readonly optionId: string;
  readonly previewId: string;
  readonly projectId: string;
  readonly resultSnapshotSha256: string;
  readonly schemaVersion: "c12-option-confirmation-v1";
}

export interface RenderSpecificationReference {
  readonly catalogReleaseId: string;
  readonly catalogReleaseSha256: string;
  readonly specificationId: string;
  readonly specificationRevision: number;
  readonly specificationRevisionSha256: string;
}

export interface RenderSourceReference {
  readonly projectId: string;
  readonly sceneArtifactId: string;
  readonly sceneGlbSha256: string;
  readonly sceneId: string;
  readonly sceneJobId: string;
  readonly sceneManifestSha256: string;
  readonly sourceSnapshotSha256: string;
  readonly specification?: RenderSpecificationReference;
}

export interface RenderEligibleSource {
  readonly cameras: readonly { readonly cameraId: string; readonly label: string }[];
  readonly label: string;
  readonly source: RenderSourceReference;
}

export interface RenderEligibleSourcesResponse {
  readonly projectId: string;
  readonly schemaVersion: "c14-render-eligible-sources-v1";
  readonly sources: readonly RenderEligibleSource[];
}

export type ContinuityOperationId = "getOptionConfirmation" | "listRenderEligibleSources";
export interface ContinuityTransportRequest {
  readonly method: "GET";
  readonly operationId: ContinuityOperationId;
  readonly path: string;
}
export interface ContinuityTransportResponse {
  readonly body: unknown;
  readonly status: number;
}
export type ContinuityTransport = (
  request: ContinuityTransportRequest,
) => Promise<ContinuityTransportResponse>;

export class ContinuityApiError extends Error {
  constructor(
    readonly code: "INVALID_RESPONSE" | "REQUEST_FAILED",
    message: string,
    readonly status: number,
  ) {
    super(message);
    this.name = "ContinuityApiError";
  }
}

const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
const sha256Pattern = /^[a-f0-9]{64}$/u;
const rfc3339Pattern = /^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:Z|[+-]\\d{2}:\\d{2})$/u;
function record(value: unknown): Record<string, unknown> | undefined {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}
function exactKeys(value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): boolean {
  const allowed = new Set([...required, ...optional]);
  return required.every((key) => key in value) && Object.keys(value).every((key) => allowed.has(key));
}
function uuid(value: unknown): value is string {
  return typeof value === "string" && uuidPattern.test(value);
}
function sha256(value: unknown): value is string {
  return typeof value === "string" && sha256Pattern.test(value);
}
function positiveInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value > 0;
}
function label(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0 && value.length <= 160;
}
function invalid(): never {
  throw new ContinuityApiError("INVALID_RESPONSE", "The response did not match the pinned continuity contract.", 502);
}

function decodeConfirmation(value: unknown, projectId: string, optionId: string): OptionConfirmation {
  const item = record(value);
  const keys = ["branchId", "branchRevision", "commitId", "confirmedAt", "confirmedBy", "id", "idempotencyKey", "optionId", "previewId", "projectId", "resultSnapshotSha256", "schemaVersion"];
  if (
    item === undefined || !exactKeys(item, keys) || !uuid(item.branchId) ||
    !positiveInteger(item.branchRevision) || !uuid(item.commitId) ||
    typeof item.confirmedAt !== "string" || !rfc3339Pattern.test(item.confirmedAt) ||
    !Number.isFinite(Date.parse(item.confirmedAt)) ||
    !uuid(item.confirmedBy) || !uuid(item.id) || !uuid(item.idempotencyKey) ||
    !uuid(item.optionId) || !uuid(item.previewId) || !uuid(item.projectId) ||
    !sha256(item.resultSnapshotSha256) || item.schemaVersion !== "c12-option-confirmation-v1" ||
    item.projectId !== projectId || item.optionId !== optionId
  ) invalid();
  return item as unknown as OptionConfirmation;
}

function decodeSpecification(value: unknown): RenderSpecificationReference {
  const item = record(value);
  const keys = ["catalogReleaseId", "catalogReleaseSha256", "specificationId", "specificationRevision", "specificationRevisionSha256"];
  if (
    item === undefined || !exactKeys(item, keys) || !uuid(item.catalogReleaseId) ||
    !sha256(item.catalogReleaseSha256) || !uuid(item.specificationId) ||
    !positiveInteger(item.specificationRevision) || !sha256(item.specificationRevisionSha256)
  ) invalid();
  return item as unknown as RenderSpecificationReference;
}

function decodeEligibleSources(value: unknown, projectId: string): RenderEligibleSourcesResponse {
  const response = record(value);
  if (
    response === undefined || !exactKeys(response, ["projectId", "schemaVersion", "sources"]) ||
    response.projectId !== projectId || response.schemaVersion !== "c14-render-eligible-sources-v1" ||
    !Array.isArray(response.sources) || response.sources.length > 100
  ) invalid();
  let previousSceneJobId: string | undefined;
  const sources = response.sources.map((value) => {
    const eligible = record(value);
    const source = record(eligible?.source);
    if (
      eligible === undefined || !exactKeys(eligible, ["cameras", "label", "source"]) ||
      !label(eligible.label) || !Array.isArray(eligible.cameras) || eligible.cameras.length < 1 ||
      eligible.cameras.length > 64 || source === undefined ||
      !exactKeys(source, ["projectId", "sceneArtifactId", "sceneGlbSha256", "sceneId", "sceneJobId", "sceneManifestSha256", "sourceSnapshotSha256"], ["specification"]) ||
      source.projectId !== projectId || !uuid(source.sceneArtifactId) || !sha256(source.sceneGlbSha256) ||
      !uuid(source.sceneId) || !uuid(source.sceneJobId) || !sha256(source.sceneManifestSha256) ||
      !sha256(source.sourceSnapshotSha256) ||
      (previousSceneJobId !== undefined && previousSceneJobId >= source.sceneJobId)
    ) invalid();
    if (source.specification !== undefined) decodeSpecification(source.specification);
    previousSceneJobId = source.sceneJobId;
    let previousCameraId: string | undefined;
    for (const value of eligible.cameras) {
      const camera = record(value);
      if (
        camera === undefined || !exactKeys(camera, ["cameraId", "label"]) || !uuid(camera.cameraId) ||
        !label(camera.label) || (previousCameraId !== undefined && previousCameraId >= camera.cameraId)
      ) invalid();
      previousCameraId = camera.cameraId;
    }
    return eligible as unknown as RenderEligibleSource;
  });
  return { projectId, schemaVersion: "c14-render-eligible-sources-v1", sources };
}

function segment(value: string): string {
  if (!uuid(value)) throw new TypeError("Continuity path identifiers must be UUIDs.");
  return encodeURIComponent(value);
}
async function ok(transport: ContinuityTransport, request: ContinuityTransportRequest): Promise<unknown> {
  const response = await transport(request);
  if (response.status < 200 || response.status >= 300) {
    throw new ContinuityApiError("REQUEST_FAILED", "The continuity request failed.", response.status);
  }
  return response.body;
}

export class CrossDeviceContinuityClient {
  constructor(private readonly transport: ContinuityTransport) {}

  async getOptionConfirmation(projectId: string, jobId: string, optionId: string): Promise<OptionConfirmation> {
    const path = \`/v1/projects/\${segment(projectId)}/design-option-jobs/\${segment(jobId)}/options/\${segment(optionId)}/confirmation\`;
    return decodeConfirmation(await ok(this.transport, { method: "GET", operationId: "getOptionConfirmation", path }), projectId, optionId);
  }

  async listRenderEligibleSources(projectId: string): Promise<RenderEligibleSourcesResponse> {
    const path = \`/v1/projects/\${segment(projectId)}/render-eligible-sources\`;
    return decodeEligibleSources(await ok(this.transport, { method: "GET", operationId: "listRenderEligibleSources", path }), projectId);
  }
}

export function createFetchContinuityTransport(options: {
  readonly baseUrl: string;
  readonly bearerToken: () => Promise<string>;
  readonly fetch?: typeof fetch;
}): ContinuityTransport {
  const fetchImplementation = options.fetch ?? fetch;
  return async (request) => {
    const token = await options.bearerToken();
    const url = new URL(request.path, options.baseUrl);
    if (
      (url.protocol !== "https:" &&
        !(url.protocol === "http:" && ["127.0.0.1", "::1", "localhost"].includes(url.hostname))) ||
      token.length < 1 ||
      /[\\r\\n]/u.test(token)
    ) {
      throw new ContinuityApiError("REQUEST_FAILED", "The continuity transport configuration is invalid.", 0);
    }
    const response = await fetchImplementation(url, {
      cache: "no-store",
      headers: { accept: "application/json, application/problem+json", authorization: \`Bearer \${token}\` },
      method: "GET",
    });
    const bytes = await response.arrayBuffer();
    if (bytes.byteLength > 1_000_000) {
      throw new ContinuityApiError("INVALID_RESPONSE", "The continuity response exceeded its size bound.", 502);
    }
    let text: string;
    try {
      text = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
    } catch {
      throw new ContinuityApiError("INVALID_RESPONSE", "The continuity response was not valid UTF-8.", 502);
    }
    let body: unknown;
    try { body = JSON.parse(text) as unknown; } catch { body = undefined; }
    return { body, status: response.status };
  };
}
`;
}

function swiftPackage() {
  return `// swift-tools-version: 6.0
// ${banner} Do not edit.
import PackageDescription

let package = Package(
    name: "CrossDeviceContinuityClient",
    platforms: [.iOS(.v17), .macOS(.v13)],
    products: [.library(name: "CrossDeviceContinuityClient", targets: ["CrossDeviceContinuityClient"])],
    targets: [
        .target(name: "CrossDeviceContinuityClient"),
        .testTarget(name: "CrossDeviceContinuityClientTests", dependencies: ["CrossDeviceContinuityClient"]),
    ]
)
`;
}

function swiftSource() {
  return `// ${banner} Do not edit.
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

public enum ContinuityContract {
    public static let generatorVersion = "${generatorVersion}"
    public static let openAPISHA256 = "${openApiSha256}"
    public static let openAPIVersion = "3.1.2"
    public static let version = "c14-cross-device-continuity-v1"
}

public struct OptionConfirmation: Codable, Equatable, Sendable {
    public let branchId: UUID
    public let branchRevision: Int
    public let commitId: UUID
    public let confirmedAt: String
    public let confirmedBy: UUID
    public let id: UUID
    public let idempotencyKey: UUID
    public let optionId: UUID
    public let previewId: UUID
    public let projectId: UUID
    public let resultSnapshotSha256: String
    public let schemaVersion: String
}

public struct RenderSpecificationReference: Codable, Equatable, Sendable {
    public let catalogReleaseId: UUID
    public let catalogReleaseSha256: String
    public let specificationId: UUID
    public let specificationRevision: Int
    public let specificationRevisionSha256: String
}

public struct RenderSourceReference: Codable, Equatable, Sendable {
    public let projectId: UUID
    public let sceneArtifactId: UUID
    public let sceneGlbSha256: String
    public let sceneId: UUID
    public let sceneJobId: UUID
    public let sceneManifestSha256: String
    public let sourceSnapshotSha256: String
    public let specification: RenderSpecificationReference?
}

public struct RenderEligibleCamera: Codable, Equatable, Sendable {
    public let cameraId: UUID
    public let label: String
}

public struct RenderEligibleSource: Codable, Equatable, Sendable {
    public let cameras: [RenderEligibleCamera]
    public let label: String
    public let source: RenderSourceReference
}

public struct RenderEligibleSourcesResponse: Codable, Equatable, Sendable {
    public let projectId: UUID
    public let schemaVersion: String
    public let sources: [RenderEligibleSource]
}

public enum ContinuityClientError: Error, Equatable, Sendable {
    case invalidBaseURL
    case invalidResponse
    case requestFailed(status: Int)
}

public struct CrossDeviceContinuityClient: Sendable {
    private let baseURL: URL
    private let bearerToken: @Sendable () async throws -> String
    private let session: URLSession

    public init(
        baseURL: URL,
        session: URLSession = CrossDeviceContinuityClient.ephemeralSession(),
        bearerToken: @escaping @Sendable () async throws -> String
    ) {
        self.baseURL = baseURL
        self.session = session
        self.bearerToken = bearerToken
    }

    public static func ephemeralSession() -> URLSession {
        let configuration = URLSessionConfiguration.ephemeral
        configuration.requestCachePolicy = .reloadIgnoringLocalAndRemoteCacheData
        configuration.urlCache = nil
        return URLSession(configuration: configuration)
    }

    public static func optionConfirmationPath(projectId: UUID, jobId: UUID, optionId: UUID) -> String {
        "/v1/projects/\\(projectId.uuidString.lowercased())/design-option-jobs/\\(jobId.uuidString.lowercased())/options/\\(optionId.uuidString.lowercased())/confirmation"
    }

    public static func renderEligibleSourcesPath(projectId: UUID) -> String {
        "/v1/projects/\\(projectId.uuidString.lowercased())/render-eligible-sources"
    }

    public func getOptionConfirmation(projectId: UUID, jobId: UUID, optionId: UUID) async throws -> OptionConfirmation {
        let data = try await getData(path: Self.optionConfirmationPath(projectId: projectId, jobId: jobId, optionId: optionId))
        guard Self.validConfirmationJSON(data) else { throw ContinuityClientError.invalidResponse }
        let value: OptionConfirmation = try Self.decode(data)
        guard value.projectId == projectId, value.optionId == optionId,
              value.branchRevision > 0, value.schemaVersion == "c12-option-confirmation-v1",
              Self.validTimestamp(value.confirmedAt), Self.validSHA256(value.resultSnapshotSha256)
        else { throw ContinuityClientError.invalidResponse }
        return value
    }

    public func listRenderEligibleSources(projectId: UUID) async throws -> RenderEligibleSourcesResponse {
        let data = try await getData(path: Self.renderEligibleSourcesPath(projectId: projectId))
        guard Self.validEligibilityJSON(data) else { throw ContinuityClientError.invalidResponse }
        let value: RenderEligibleSourcesResponse = try Self.decode(data)
        guard value.projectId == projectId, value.schemaVersion == "c14-render-eligible-sources-v1",
              value.sources.count <= 100 else { throw ContinuityClientError.invalidResponse }
        var previousSceneJobId: String?
        for eligible in value.sources {
            let sceneJobId = eligible.source.sceneJobId.uuidString.lowercased()
            guard eligible.source.projectId == projectId, !eligible.cameras.isEmpty,
                  eligible.cameras.count <= 64, !eligible.label.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                  eligible.label.count <= 160, previousSceneJobId.map({ $0 < sceneJobId }) ?? true,
                  Self.validSource(eligible.source) else { throw ContinuityClientError.invalidResponse }
            previousSceneJobId = sceneJobId
            var previousCameraId: String?
            for camera in eligible.cameras {
                let cameraId = camera.cameraId.uuidString.lowercased()
                guard !camera.label.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                      camera.label.count <= 160, previousCameraId.map({ $0 < cameraId }) ?? true
                else { throw ContinuityClientError.invalidResponse }
                previousCameraId = cameraId
            }
        }
        return value
    }

    private func getData(path: String) async throws -> Data {
        guard let url = URL(string: path, relativeTo: baseURL)?.absoluteURL,
              url.scheme == "https" || (url.scheme == "http" && ["127.0.0.1", "::1", "localhost"].contains(url.host ?? ""))
        else {
            throw ContinuityClientError.invalidBaseURL
        }
        let token = try await bearerToken()
        guard !token.isEmpty, !token.contains("\\n"), !token.contains("\\r") else {
            throw ContinuityClientError.invalidResponse
        }
        var request = URLRequest(url: url, cachePolicy: .reloadIgnoringLocalAndRemoteCacheData)
        request.httpMethod = "GET"
        request.setValue("application/json, application/problem+json", forHTTPHeaderField: "Accept")
        request.setValue("no-store", forHTTPHeaderField: "Cache-Control")
        request.setValue("Bearer \\(token)", forHTTPHeaderField: "Authorization")
        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse else { throw ContinuityClientError.invalidResponse }
        guard (200..<300).contains(http.statusCode) else {
            throw ContinuityClientError.requestFailed(status: http.statusCode)
        }
        guard data.count <= 1_000_000 else { throw ContinuityClientError.invalidResponse }
        return data
    }

    private static func decode<Response: Decodable>(_ data: Data) throws -> Response {
        do { return try JSONDecoder().decode(Response.self, from: data) }
        catch { throw ContinuityClientError.invalidResponse }
    }

    private static func exactKeys(
        _ object: [String: Any],
        required: Set<String>,
        optional: Set<String> = []
    ) -> Bool {
        Set(object.keys).isSubset(of: required.union(optional)) && required.isSubset(of: Set(object.keys))
    }

    static func validConfirmationJSON(_ data: Data) -> Bool {
        guard let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else { return false }
        return exactKeys(object, required: [
            "branchId", "branchRevision", "commitId", "confirmedAt", "confirmedBy", "id",
            "idempotencyKey", "optionId", "previewId", "projectId", "resultSnapshotSha256", "schemaVersion",
        ])
    }

    static func validEligibilityJSON(_ data: Data) -> Bool {
        guard let response = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              exactKeys(response, required: ["projectId", "schemaVersion", "sources"]),
              let sources = response["sources"] as? [[String: Any]], sources.count <= 100
        else { return false }
        for eligible in sources {
            guard exactKeys(eligible, required: ["cameras", "label", "source"]),
                  let cameras = eligible["cameras"] as? [[String: Any]],
                  !cameras.isEmpty, cameras.count <= 64,
                  cameras.allSatisfy({ exactKeys($0, required: ["cameraId", "label"]) }),
                  let source = eligible["source"] as? [String: Any],
                  exactKeys(
                    source,
                    required: ["projectId", "sceneArtifactId", "sceneGlbSha256", "sceneId", "sceneJobId", "sceneManifestSha256", "sourceSnapshotSha256"],
                    optional: ["specification"]
                  )
            else { return false }
            if let specification = source["specification"] {
                guard let specification = specification as? [String: Any],
                      exactKeys(specification, required: ["catalogReleaseId", "catalogReleaseSha256", "specificationId", "specificationRevision", "specificationRevisionSha256"])
                else { return false }
            }
        }
        return true
    }

    private static func validSource(_ source: RenderSourceReference) -> Bool {
        validSHA256(source.sceneGlbSha256) && validSHA256(source.sceneManifestSha256) &&
        validSHA256(source.sourceSnapshotSha256) && source.specification.map {
            $0.specificationRevision > 0 && validSHA256($0.catalogReleaseSha256) &&
            validSHA256($0.specificationRevisionSha256)
        } ?? true
    }

    private static func validSHA256(_ value: String) -> Bool {
        value.range(of: "^[a-f0-9]{64}$", options: .regularExpression) != nil
    }

    private static func validTimestamp(_ value: String) -> Bool {
        if ISO8601DateFormatter().date(from: value) != nil { return true }
        let fractional = ISO8601DateFormatter()
        fractional.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return fractional.date(from: value) != nil
    }
}
`;
}

function swiftTest() {
  return `// ${banner} Do not edit.
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Testing
@testable import CrossDeviceContinuityClient

private enum StubError: Error {
    case invalidRequest
}

private final class URLProtocolStub: URLProtocol, @unchecked Sendable {
    nonisolated(unsafe) static var handler: (@Sendable (URLRequest) throws -> (HTTPURLResponse, Data))?

    override class func canInit(with request: URLRequest) -> Bool { true }
    override class func canonicalRequest(for request: URLRequest) -> URLRequest { request }

    override func startLoading() {
        do {
            guard let handler = Self.handler else { throw StubError.invalidRequest }
            let (response, data) = try handler(request)
            client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
            client?.urlProtocol(self, didLoad: data)
            client?.urlProtocolDidFinishLoading(self)
        } catch {
            client?.urlProtocol(self, didFailWithError: error)
        }
    }

    override func stopLoading() {}
}

@Test func contractPinsAndPathsAreStable() throws {
    #expect(ContinuityContract.openAPIVersion == "3.1.2")
    #expect(ContinuityContract.openAPISHA256 == "${openApiSha256}")
    let project = try #require(UUID(uuidString: "14000000-0000-4000-8000-000000000001"))
    let job = try #require(UUID(uuidString: "12000000-0000-4000-8000-000000000002"))
    let option = try #require(UUID(uuidString: "12000000-0000-4000-8000-000000000003"))
    #expect(CrossDeviceContinuityClient.renderEligibleSourcesPath(projectId: project) == "/v1/projects/14000000-0000-4000-8000-000000000001/render-eligible-sources")
    #expect(CrossDeviceContinuityClient.optionConfirmationPath(projectId: project, jobId: job, optionId: option) == "/v1/projects/14000000-0000-4000-8000-000000000001/design-option-jobs/12000000-0000-4000-8000-000000000002/options/12000000-0000-4000-8000-000000000003/confirmation")
}

@Test func unknownResponseFieldsFailClosed() {
    let confirmation = Data(#"{"branchId":null,"branchRevision":null,"commitId":null,"confirmedAt":null,"confirmedBy":null,"id":null,"idempotencyKey":null,"optionId":null,"previewId":null,"projectId":null,"resultSnapshotSha256":null,"schemaVersion":null,"privateToken":"forged"}"#.utf8)
    let eligibility = Data(#"{"projectId":null,"schemaVersion":null,"sources":[],"privateToken":"forged"}"#.utf8)
    #expect(!CrossDeviceContinuityClient.validConfirmationJSON(confirmation))
    #expect(!CrossDeviceContinuityClient.validEligibilityJSON(eligibility))
}

@Test func transportUsesAuthenticatedUncachedJSONGet() async throws {
    let configuration = URLSessionConfiguration.ephemeral
    configuration.protocolClasses = [URLProtocolStub.self]
    configuration.requestCachePolicy = .reloadIgnoringLocalAndRemoteCacheData
    configuration.urlCache = nil
    let session = URLSession(configuration: configuration)
    let project = try #require(UUID(uuidString: "14000000-0000-4000-8000-000000000001"))
    let job = try #require(UUID(uuidString: "12000000-0000-4000-8000-000000000002"))
    let option = try #require(UUID(uuidString: "12000000-0000-4000-8000-000000000003"))
    URLProtocolStub.handler = { request in
        guard request.url?.absoluteString == "https://continuity.example/v1/projects/14000000-0000-4000-8000-000000000001/design-option-jobs/12000000-0000-4000-8000-000000000002/options/12000000-0000-4000-8000-000000000003/confirmation",
              request.httpMethod == "GET",
              request.value(forHTTPHeaderField: "Accept") == "application/json, application/problem+json",
              request.value(forHTTPHeaderField: "Cache-Control") == "no-store",
              request.value(forHTTPHeaderField: "Authorization") == "Bearer fixture-token",
              request.cachePolicy == .reloadIgnoringLocalAndRemoteCacheData,
              let url = request.url,
              let response = HTTPURLResponse(url: url, statusCode: 200, httpVersion: "HTTP/1.1", headerFields: ["Content-Type": "application/json"])
        else { throw StubError.invalidRequest }
        let body = #"{"branchId":"12000000-0000-4000-8000-000000000004","branchRevision":1,"commitId":"12000000-0000-4000-8000-000000000005","confirmedAt":"2026-08-26T00:00:00Z","confirmedBy":"12000000-0000-4000-8000-000000000006","id":"12000000-0000-4000-8000-000000000007","idempotencyKey":"12000000-0000-4000-8000-000000000008","optionId":"12000000-0000-4000-8000-000000000003","previewId":"12000000-0000-4000-8000-000000000009","projectId":"14000000-0000-4000-8000-000000000001","resultSnapshotSha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","schemaVersion":"c12-option-confirmation-v1"}"#
        return (response, Data(body.utf8))
    }
    defer { URLProtocolStub.handler = nil }
    let client = CrossDeviceContinuityClient(
        baseURL: try #require(URL(string: "https://continuity.example")),
        session: session,
        bearerToken: { "fixture-token" }
    )
    let confirmation = try await client.getOptionConfirmation(projectId: project, jobId: job, optionId: option)
    #expect(confirmation.optionId == option)
    #expect(confirmation.projectId == project)
}
`;
}

const outputs = new Map([
  [
    typescriptPath,
    await prettier.format(typescriptSource(), {
      ...prettierConfig,
      filepath: typescriptPath,
    }),
  ],
  [swiftPackagePath, swiftPackage()],
  [swiftSourcePath, swiftSource()],
  [swiftTestPath, swiftTest()],
]);
const check = process.argv.includes("--check");
for (const [outputPath, content] of outputs) {
  if (check) {
    const current = await readFile(outputPath, "utf8").catch(() => undefined);
    if (current !== content)
      throw new Error(`Generated output is stale: ${path.relative(root, outputPath)}`);
  } else {
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, content, "utf8");
  }
}
