import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { roomPlanNormalizedSchema } from "../../../packages/contracts/src/c7.js";

const fixturePath = resolve(
  process.cwd(),
  "tests/mobile/capture/fixtures/golden-normalized-roomplan.json",
);
const adversarialFixtures = [
  "adversarial-duplicate-entity.json",
  "adversarial-floating-coordinate.json",
  "adversarial-missing-parent.json",
  "adversarial-unknown-field.json",
] as const;

// Mirrored by C7GoldenContractUITests.swift. A digest change requires an
// intentional update in both languages and is never generated by a producer.
const crossLanguageGoldenSha256 =
  "f793e3b63d8342931be13c2931062ebd3b9d44328cab5f59e91729571cec9f74";

describe("C7 cross-language normalized RoomPlan golden", () => {
  it("accepts the exact visibly synthetic byte stream with the frozen TypeScript schema", async () => {
    const bytes = await readFile(fixturePath);
    expect(createHash("sha256").update(bytes).digest("hex")).toBe(crossLanguageGoldenSha256);

    const parsed: unknown = JSON.parse(bytes.toString("utf8"));
    const normalized = roomPlanNormalizedSchema.parse(parsed);
    expect(normalized.schemaVersion).toBe("c7-roomplan-normalized-v1");
    expect(normalized.rooms.map(({ userLabel }) => userLabel)).toEqual([
      "Synthetic room A",
      "Synthetic room B",
    ]);
    expect(normalized).toEqual(parsed);
  });

  for (const fixtureName of adversarialFixtures) {
    it(`rejects the shared adversarial fixture ${fixtureName}`, async () => {
      const bytes = await readFile(
        resolve(process.cwd(), "tests/mobile/capture/fixtures", fixtureName),
      );
      const parsed: unknown = JSON.parse(bytes.toString("utf8"));
      expect(roomPlanNormalizedSchema.safeParse(parsed).success).toBe(false);
    });
  }

  it("rejects missing identifiers and non-integer normalized values without coercion", async () => {
    const parsed = JSON.parse(await readFile(fixturePath, "utf8")) as Record<string, unknown>;
    const surfaces = requireArray(parsed.surfaces);
    const firstSurface = requireRecord(surfaces[0]);

    const missingIdentifier = structuredClone(parsed);
    delete requireRecord(requireArray(missingIdentifier.surfaces)[0]).sourceIdentifier;
    expect(roomPlanNormalizedSchema.safeParse(missingIdentifier).success).toBe(false);

    const floatingCoordinate = structuredClone(parsed);
    const floatingTransform = requireRecord(
      requireRecord(requireArray(floatingCoordinate.surfaces)[0]).transform,
    );
    requireRecord(floatingTransform.translationMicrometres).x = 0.25;
    expect(roomPlanNormalizedSchema.safeParse(floatingCoordinate).success).toBe(false);

    expect(firstSurface.sourceIdentifier).toBe("55555555-5555-4555-8555-555555555551");
  });
});

function requireArray(value: unknown): unknown[] {
  if (!Array.isArray(value)) throw new Error("Expected an array fixture value.");
  return value;
}

function requireRecord(value: unknown): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("Expected an object fixture value.");
  }
  return value as Record<string, unknown>;
}
